export const cityConstants = {
  ADD_CITY_SUCCESS: "ADD_CITY_SUCCESS",
  ADD_CITY_FAILURE: "ADD_CITY_FAILURE",

  DELETE_CITY_SUCCESS: "DELETE_CITY_SUCCESS",
  DELETE_CITY_FAILURE: "DELETE_CITY_FAILURE",

  GET_SAVED_CITIES_SUCCESS: "GET_SAVED_CITIES_SUCCESS"
};
